language: node_js
node_js:
  - "12"
  - "13"
install:
  - npm ci
  - cd packages/detect-link-type && npm ci && cd ..

script:
  - npm t

# Test the building process is ok too
after_success:
  - npm run build
