name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'This is your first issue on our repo :) Thank you!'
        pr-message: 'You are breathtaking. Thank you so much for your contribution!'
